### ISSUE TITLE
Code for Franka Panda robot

### ISSUE THREAD

**Issue by trannguyenle95** [columbia-ai-robotics/diffusion_policy#13]
Hi,

In the paper, you mentioned that you executed the policy on two different robots: UR5 and Franka. Is it possible to release the code for Franka as well? Thanks!

**Comment by cheng-chi** [comment]
Hi @trannguyenle95, unfortunately, the Franka experiments used TRI's proprietary software infrastructure and, therefore cannot be open-sourced. However, building a pipeline for Franka should be fairly straightforward if you simply replace our RTDEInterpolationController with [Deoxys](https://ut-austin-rpl.github.io/deoxys-docs/html/getting_started/quick_start_guide.html).
