### ISSUE TITLE
Question: about the franka's end-effector

### ISSUE THREAD

**Issue by AlbertTan404** [columbia-ai-robotics/diffusion_policy#15]
Thanks for your novel work!

I'm curious about what's the end-effector of the panda robot in the 6DoF Flipping task? Did you print that or that's an official/third party component? I'd appreciate it if you could show me the way.

**Comment by cheng-chi** [comment]
Hi @AlbertTan404, the finger is 3D printed using [NinjaFlex TPU](https://ninjatek.com/shop/ninjaflex/). Here is the onshape link for its [CAD model](https://cad.onshape.com/documents/bec64ccbab1c554f3cfea1e3/w/b54dc11dc0673c6df11e275c/e/67993c5ee6c667ded1e4c5be?renderMode=0&uiState=64fa57db3b8b5f4ef163eead).

**Comment by AlbertTan404** [comment]
> Hi @AlbertTan404, the finger is 3D printed using [NinjaFlex TPU](https://ninjatek.com/shop/ninjaflex/). Here is the onshape link for its [CAD model](https://cad.onshape.com/documents/bec64ccbab1c554f3cfea1e3/w/b54dc11dc0673c6df11e275c/e/67993c5ee6c667ded1e4c5be?renderMode=0&uiState=64fa57db3b8b5f4ef163eead).

Really appreciate for your reply!
