### ISSUE TITLE
Question about the controller used for diffusion policy

### ISSUE THREAD

**Issue by wkwan7** [columbia-ai-robotics/diffusion_policy#8]
Hi,

Thank you for your fantastic work and beautiful code! As described in the paper, you use position control instead of velocity control on the robomimic tasks for diffusion policy. However, I didn't find the corresponding changes to the robomimic environment controller in the code, except for the use of "abs_action". Did I miss something?

Thank you so much for your time.

Best regards,

Weikang

**Comment by cheng-chi** [comment]
Hi @wkwan7, good question. The conversion to positional control is done in 2 parts:
1. Robomimic envs already have built-in support for positional control (they actually implemented velocity control on top of positional controller). This behavior is controled by "control_delta" argument for their env controllers, which is set to false by the abs_action flag [here](https://github.com/columbia-ai-robotics/diffusion_policy/blob/74b6391737ce2594258fdda48e6729aae310d7ed/diffusion_policy/env_runner/robomimic_lowdim_runner.py#L109)
2. Robomimic's hdf5 datasets also need be converted to positional control using [this script](https://github.com/columbia-ai-robotics/diffusion_policy/blob/main/diffusion_policy/scripts/robomimic_dataset_conversion.py) that outputs a new copy of the hdf5 with the only difference being the 7DoF action overwritten to positional actions. This script optionally verifies that the resulting positional actions result in the same robot behavior if you set the "--eval-dir" variable. If you are only interested in reproducing our result, the converted hdf5 files are already provided through [datasets](https://diffusion-policy.cs.columbia.edu/data/training/) hosted on our server.

**Comment by wkwan7** [comment]
Thank you so much for your quick response! This was really helpful.
